### ISSUE TITLE
Update API documentation please

### ISSUE THREAD

**Issue by keadeish** [LCozzoli/SMS-Activate.org#5]
Hey,
Could you please update the documentation? I get a lot of type errors when I paste the README.md into a ts project. Thank you!

**Comment by LCozzoli** [comment]
Hello, using ESLint ?

**Comment by keadeish** [comment]
Hey, yes

**Comment by keadeish** [comment]
✖ 94 problems (90 errors, 4 warnings)
  8 errors and 0 warnings potentially fixable with the `--fix` option. - that's what i get

**Comment by LCozzoli** [comment]
I changed the `async (number: SMSNumber)`, is it fixed now?

**Comment by keadeish** [comment]
That does work although I’m still not receiving codes. 

Everything executes until number.getCode(180).then(async code => {…

**Comment by LCozzoli** [comment]
Can you turn on debugs please
Define `SMS_ACTIVATE_DEBUG=true` in your .env file

**Comment by keadeish** [comment]
Yeah sure, is there any way for me to post screenshots?

**Comment by LCozzoli** [comment]
My discord is SegFault#0001

**Comment by keadeish** [comment]
Added @LCozzoli - user is 'Psychician#4502'
